#!/bin/bash
# Copyright (C) 2010 Stéphane Robert Richard.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the project nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.



# Tiny wrapper around ant for the ease of preconfiguration
# IMPORTANT:
# All configurations entries defined in your recipes are internally loaded with a prefix of 'cfg.'
# If you need to override some of these configurations right at the command line, you must prefix them.
# ie: To override 'processors', use -Dcfg.processors=${value}

declare ANT_ARGS="
	-Dcfg.processors=$(cat /proc/cpuinfo | grep processor | wc -l)
	-logger org.apache.tools.ant.listener.AnsiColorLogger
	"

show_usage(){
	echo "
USAGE: $0 [recipe] [target]
WHERE 
[recipe] is one of:
$recipes
[target] is one of:"
	ant -p | grep '^ ' | sed 's/^ /    /'
}

for arg in "$@"; do
	case "$arg" in
		-h|--help)
			show_usage
			exit
			;;
		-d|--debug)
			shift
			ANT_ARGS="$ANT_ARGS -d"
			;;
		*)
			if [[ $# == 2 ]]; then
				break
			else
				echo Unknow argument $arg
				exit 0
			fi
	esac
done

export ANT_ARGS

ant -Drecipe.name=${1:-default} $2
